# All LLM configurations default to the Gemini models
llms:
  memory_relevance_model: "gemini-2.0-flash"
  supervisor_model: "gemini-2.0-flash-thinking-exp"
  member_default_model: "gemini-2.0-flash-thinking-exp"
  memory_processor_model: "gemini-2.0-flash-thinking-exp"
  math_agent_model: "gemini-2.0-flash-thinking-exp"
  image_description_model: "gemini-2.0-flash"
  json_ensure_model: "gpt-4o-json"
features:
  memory:
    enable_retrieval: false
    enable_updater: true
    enable_pinecone_update: false
  email:
    draft_mode: true
    user_email: "example@domain.com" 