import os
from setuptools import setup, find_packages

setup(
    name="Homework Agent",
    version="0.0.1",
    packages=find_packages(),
    install_requires=[
        "python-dotenv",
        "loguru",
        "langgraph",
        "langchain",
        "numpy",
        "pyautogui",
        "Pillow",
        "pywin32",
        "fastapi",
        "mss",
        "azure-cognitiveservices-vision-computervision",
        "opencv-python",
        "langchain_anthropic",
        "langchain_openai", 
        "langchain_google_genai",
        "langchain_xai",
        "langchain_deepseek",
        "pinecone",
        "pinecone-client",
        "py-zerox",
    ],
    author="Zhiyuan Zhang (John Zhang)",
    author_email="zhiyuan.zhang0206@gmail.com",
    description="An multi-agent system for homework completion.",
    long_description=open("readme.md", encoding="utf-8").read() if os.path.exists("readme.md") else "",
    long_description_content_type="text/markdown",
)